import { App, Notice, TFile, TFolder, normalizePath } from "obsidian";
import * as fs from "fs";
import * as path from "path";
import { ProjectFrontmatter, ProjectLink, effectiveLinks } from "./project";
import { vaultBasePath } from "../util/obsidian";

// Create or update a project's _PROJECT.md, then (re)generate .claude/settings.json
// and CLAUDE.md. Returns the _PROJECT.md file, or null if no target could be found.
export async function saveProject(
  app: App,
  file: TFile | null,
  folder: TFolder | null,
  data: ProjectFrontmatter,
): Promise<TFile | null> {
  let target = file;
  if (!target) {
    if (!folder) { new Notice("No target folder"); return null; }
    target = await app.vault.create(normalizePath(folder.path + "/_PROJECT.md"), "");
  }
  await app.fileManager.processFrontMatter(target, (fm) => {
    fm.title = data.title;
    delete fm.workfront; // migrated into `links`
    if (data.links?.length) fm.links = data.links; else delete fm.links;
    fm.read_paths  = data.read_paths  ?? [];
    fm.write_paths = data.write_paths ?? [];
  });

  writeClaudeSettings(app, target, data);
  writeClaudeMd(app, target, data);
  new Notice("_PROJECT.md saved");
  return target;
}

// Update only the links list in _PROJECT.md (deduped), dropping legacy workfront.
export async function saveLinks(app: App, file: TFile, links: ProjectLink[]): Promise<void> {
  const seen = new Set<string>();
  const clean = links
    .map((l) => ({ label: (l.label || l.url).trim(), url: l.url.trim() }))
    .filter((l) => l.url && !seen.has(l.url) && seen.add(l.url));

  await app.fileManager.processFrontMatter(file, (fm) => {
    delete fm.workfront;
    if (clean.length) fm.links = clean; else delete fm.links;
  });
}

// Write .claude/settings.json next to _PROJECT.md with read/write permissions.
function writeClaudeSettings(app: App, projectFile: TFile, data: ProjectFrontmatter) {
  try {
    const projDir = path.join(vaultBasePath(app), projectFile.parent!.path);

    const writes = (data.write_paths ?? []).filter((p) => path.isAbsolute(p));
    const reads  = (data.read_paths  ?? []).filter((p) => path.isAbsolute(p));
    // Read-only dirs (not also writable) need explicit access.
    const readOnly = reads.filter((p) => !writes.includes(p));

    // Edit/Write granted for the project dir + every writable path.
    const allow: string[] = [];
    for (const dir of [projDir, ...writes]) {
      allow.push(`Edit(/${dir}/**)`);
      allow.push(`Write(/${dir}/**)`);
    }

    const settings = {
      permissions: {
        defaultMode: "default",
        additionalDirectories: readOnly,
        allow,
        deny: [
          "Bash(rm:*)", "Bash(rmdir:*)", "Bash(mv:*)", "Bash(dd:*)",
          "Bash(sudo:*)", "Bash(git push:*)", "Bash(curl:*)", "Bash(wget:*)",
        ],
      },
    };

    const claudeDir = path.join(projDir, ".claude");
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.writeFileSync(path.join(claudeDir, "settings.json"), JSON.stringify(settings, null, 2) + "\n");
  } catch (e) {
    new Notice(`Could not write .claude/settings.json: ${e}`);
    console.error("[my-project-panel]", e);
  }
}

// Write/refresh CLAUDE.md routing guidance in a managed block (preserves any
// user-authored content outside the markers).
function writeClaudeMd(app: App, projectFile: TFile, data: ProjectFrontmatter) {
  try {
    const projDir = path.join(vaultBasePath(app), projectFile.parent!.path);

    const writes   = (data.write_paths ?? []).filter((p) => path.isAbsolute(p));
    const reads    = (data.read_paths  ?? []).filter((p) => path.isAbsolute(p));
    const readOnly = reads.filter((p) => !writes.includes(p));
    const firstWrite = writes[0];

    const START = "<!-- my-project:start -->";
    const END   = "<!-- my-project:end -->";

    const lines: string[] = [];
    lines.push(START);
    lines.push(`# ${data.title ?? "Project"}`);
    lines.push("");
    lines.push("Customer project. This file is auto-generated by the My Project Panel plugin — edit outside the markers only.");
    const links = effectiveLinks(data);
    if (links.length) {
      lines.push("");
      lines.push("## Links");
      lines.push("");
      for (const l of links) lines.push(`- [${l.label}](${l.url})`);
    }
    lines.push("");
    lines.push("## Locations");
    lines.push("");
    lines.push("| Purpose | Path |");
    lines.push("| --- | --- |");
    lines.push(`| Obsidian notes (this folder) | \`${projDir}\` |`);
    writes.forEach((p, i) =>
      lines.push(`| Writable files folder${writes.length > 1 ? ` #${i + 1}` : ""} | \`${p}\` |`));
    readOnly.forEach((p) => lines.push(`| Read-only reference | \`${p}\` |`));
    lines.push("");
    lines.push("## Where to write");
    lines.push("");
    if (firstWrite) {
      lines.push(`- "save the file", "write file X", "export …", or any **document/file** (xlsx, pptx, docx, pdf, etc.) → write to the **first writable files folder**: \`${firstWrite}\``);
    } else {
      lines.push("- No writable files folder configured — add one in the project settings to enable document writes.");
    }
    lines.push(`- "write a note", "summarize in X.md", "add to my notes", or any **Markdown note** → write to the **Obsidian notes folder**: \`${projDir}\``);
    lines.push("- Default: prose/notes/Markdown go to the Obsidian notes folder; documents and other files go to the first writable files folder.");
    lines.push("- Never write outside the paths allowed in `.claude/settings.json`.");
    lines.push(END);
    const block = lines.join("\n");

    const mdPath = path.join(projDir, "CLAUDE.md");
    let content = "";
    try { content = fs.readFileSync(mdPath, "utf-8"); } catch { /* new file */ }

    if (content.includes(START) && content.includes(END)) {
      const re = new RegExp(`${START}[\\s\\S]*?${END}`);
      content = content.replace(re, block);
    } else {
      content = content.trim() ? `${block}\n\n${content}` : `${block}\n`;
    }
    fs.writeFileSync(mdPath, content);
  } catch (e) {
    new Notice(`Could not write CLAUDE.md: ${e}`);
    console.error("[my-project-panel]", e);
  }
}
